server:
  port: 8084

spring:
  application:
    name: client-service
  datasource:
    url: jdbc:postgresql://localhost:5432/javafinalproject
    username: postgres
    password: beka asd2020
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
